name: workflow1
on:
  schedule:
    - cron: "50 * * * *"
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true   
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - run: ls -ltr
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        run: |
          docker build -t aimanhaikal5913/intel:maven .
          docker images
          docker login --username aimanhaikal5913 --password ${{ secrets.DOCKER_PASS }}
          docker push aimanhaikal5913/intel:maven

  test:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hostname
      - name: sleep for 30 seconds
        run: sleep 30
      - name: test step
        run: echo job2 run successfully
    needs: build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hostname
      - name: sleep for 30 seconds
        run: sleep 30
    needs: test
    if: ${{ always () }} 
