name: workflow1
on:
  schedule:
    - cron: "50 * * * *"
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      last_name: Aiman
    steps:
      - name: first step
        run: hostname
        continue-on-error: true
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - run: ls -ltr
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        run: |
          docker build -t aimanhaikal5914/gittest:latest .
          docker images
          docker push
      - name: sleep for 30 seconds
        run: |
          sleep 30
          continue-on-error: true
          eco "Firstname is $first_name. Last name is $last_name"
        env:
          first_name: Gagandeep
        if: github.event_name == 'push'
      - name: multline run
        run: |
          echo running a multiline step
          echo mkdir gagandeep
          echo "Firstname is $first_name. Last name is $last_name"
          echo touch file1
        if: runner.os != 'Windows'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hotname
      - name: sleep for 30 seconds
        run: sleep 30
      - name: test step
        run: echo job2 run successfully
    needs: build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hostname
      - name: sleep for 30 seconds
        run: sleep 30
    needs: test
    if: ${{ always () }} 
