name: workflow1
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:
  build-job:
    runs-on: ubuntu-latest
    env:
      last_name: Hassan
    steps:
      - name: first step
        run: hostname
      - name: sleep for 60 seconds
        run: echo "Firstname is $first_name. Last name is $last_name"
        env:
          first_name: Aiman
        if: github.event_name == 'push'
      - name: multline run
        run: |
          echo running a multiline step
          echo mkdir Aiman
          echo "Firstname is $first_name. Last name is $last_name"
          echo touch file1
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hostname
      - name: sleep for 60 seconds
        run: sleep 60
      - name: test step
        run: echo job2 run successfully
